name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '21 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Stale issue message'
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'enhancement,stale exempt'
          stale-pr-message: 'Stale pull request message'
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'stale exempt'
